### ISSUE TITLE
Vercel 部署后访问 404

### ISSUE THREAD

**Issue by ssfun** [LLM-Red-Team/kimi-free-api#99]
页面报错
404: NOT_FOUND
Code: NOT_FOUND
ID: hkg1::dch6n-1715418987679-8f43eed8e825

post 请求报 The page could not be found

**Comment by Vinlic** [comment]
使用文档中的命令行部署方式，不能在vercel上面直接点击部署

**Comment by ssfun** [comment]
用的 GitHub actions ，应该也算是命令行吧？
```
name: Deploy Kimi to Vercel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Vercel CLI
      run: npm i -g vercel --registry http://registry.npmmirror.com

    - name: Clone repository
      run: git clone https://github.com/LLM-Red-Team/kimi-free-api

    - name: Change directory
      run: cd kimi-free-api

    - name: Deploy to Vercel
      run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --name kimi-free-api
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
```
